### ISSUE TITLE
New theme for Joplin

### ISSUE THREAD

**Issue by bonbuggie** [rose-pine/rose-pine-theme#109]
### Link to theme repo

https://github.com/bonbuggie/joplin

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

- This is a **reskin** of [Catppuccin for Joplin](https://github.com/catppuccin/joplin)
- Only includes the **Rosé Pine Moon** theme

**Comment by mvllow** [comment]
Thank you for another theme :)

Some feedback similar to the geany repository–I think we can remove the Catppuccin license because we link to it in the readme. We can either delete the license or put Rosé Pine instead.

The colours seem to be a mix between our variants, even though branded as moon. I made a [pull request](https://github.com/rose-pine/geany/pull/1) to the geany repo to use our build tool if you're interested in trying that. That PR also unified the palette but I have not been able to test it and ensure everything works. Maybe those changes could apply to joplin as well.

Thanks again, and I'm happy to help with any changes if you would like!

**Comment by bonbuggie** [comment]
> Some feedback similar to the geany repository–I think we can remove the Catppuccin license because we link to it in the readme. We can either delete the license or put Rosé Pine instead.

Thank you for explaining this! Was not sure if I had to keep the license intact, glad you cleared that up for me!


> The colours seem to be a mix between our variants, even though branded as moon.

You're absolutely right, my apologies! I edited this theme a long time ago and did not check if I adequately followed the theme before uploading this. My mistake, won't happen again!


> I made a pull request to the geany repo to use our build tool if you're interested in trying that. That PR also unified the palette but I have not been able to test it and ensure everything works. Maybe those changes could apply to joplin as well.

That sounds awesome, I will definitely have a look at that. I'm not too familiar with the build tool but it sounds like a great idea.


I completely appreciate all your help and guidance! Thank you so much for your time and patience! <3

**Comment by bonbuggie** [comment]
SORRY - this theme is out of date!
