### ISSUE TITLE
New theme for Vivaldi

### ISSUE THREAD

**Issue by SocietasEvanescentes** [rose-pine/rose-pine-theme#119]
### Link to theme repo

https://github.com/SocietasEvanescentes/Vivaldi

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

I've created Vivaldi themes for the Rosé Pine community; the themes on the Vivaldi theme store, while good, do not provide great contrast. 

I aimed to fix this, and with me wanting to add it to the rosé pine theme website, it was essential that all the themes were easy to read.

**Comment by mvllow** [comment]
Grazie!

Few nitpicks (not necessary, just preference):

- Rename filenames to `rose-pine` etc.
- Maybe show the gallery images similar to our template (bold text and not in a details/summary) since it is just screenshot per variant

Also, please add "theme" to the GitHub topics so it will automatically be added to our website next time we build it.

Feel free to transfer at any time :)

**Comment by SocietasEvanescentes** [comment]
Done and done ✅
