### ISSUE TITLE
New theme for Bibata Original Cursors

### ISSUE THREAD

**Issue by harishnkr** [rose-pine/rose-pine-theme#91]
### Link to theme repo

https://github.com/harishnkr/Bibata-Original-Cursors

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

Created a port, might as well contribute to the main repo. Haven't tested for Windows

**Comment by mvllow** [comment]
Feel free to transfer – please rename the repo to all lowercase :)

Also, suggestions for the repo (but not blocking):

- Inline the readme images instead of having an assets folder to reduce space when cloning the repo. This can be done by dropping an image into the GitHub readme editor.
- Is the word "Original" important here? I'm not familiar with Bibata but it seems unnecessary.

Thanks for another contribution, always appreciated 💜

**Comment by harishnkr** [comment]
Cool.
I'll fix the case of the title as well as the assets folder.
Original is a variation of the cursor, there's another one called "Modern" for Bibata cursors.
I guess I'll add the "Modern" version as well and remove the Original word entirely from the repo title

**Comment by mvllow** [comment]
Added this theme to our website, linking to your repository. I'll update the site if you decide to transfer in but closing this issue for now. Thanks again for the theme!

**Comment by harishnkr** [comment]
Cool. Do transfer the repo if that's what everyone usually does. I don't have a preference for any of the options on what to do with the repo but this is what I chose by default.
